### ISSUE TITLE
Default answers type numbers are not supported

### ISSUE THREAD

**Issue by GianlucaGuarini** [GianlucaGuarini/rob#1]
Add support for default answers type `Num`
```
questions:
  age:
    question: How old are you?
    default: 10
```
